#%RAML 1.0 NamedExample
value:
  -
    aerolinea: United
    codigoVuelo: ER38sd
    destino: SFO
    origen: LAX
    fechadeSalida: May 21, 2016
    asientosDisponibles: 0
    asientosTotales: 200
    precio: 199
    tipoAvion: Boeing 737
  -
    aerolinea: Delta
    codigoVuelo: ER0945
    origen: PDX
    destino: CLE
    fechadeSalida: June 1, 2016
    asientosDisponibles: 24
    asientosTotales: 350
    precio: 450
    tipoAvion: Boeing 747